name: Docker Build and Deploy
description: Build and push Docker images to Azure Container Registry, then deploy to AKS
inputs:
    DOCKER_REPO:
      description: 'Docker repository'
      required: true
    DOCKER_FILE:
      description: 'Dockerfile path'
      required: true
    BUILD_ARGS:
      description: 'Build arguments'
      required: false
    K8S_NAMESPACE:
      description: 'Kubernetes namespace'
      required: true
    K8S_DEPLOYMENT:
      description: 'Kubernetes deployment name'
      required: true
runs:
  using: composite
  steps:
  - name: Build container image and push to Azure
    uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
    with:
      file: ${{ inputs.DOCKER_FILE }}
      tags: ${{ inputs.DOCKER_REPO }}:latest
      build-args: ${{ inputs.BUILD_ARGS }}
      push: true

  - name: Login to our Azure subscription.
    uses: azure/login@v1
    with:
      client-id: ${{ inputs.AZURE_CLIENT_ID_OIDC }}
      tenant-id: ${{ inputs.AZURE_TENANT_ID }}
      subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}

  - name: Login to Azure Container Registry
    shell: bash
    run: az acr login --name adoptopenjdkacr

  - name: Set the target Azure Kubernetes Service (AKS) cluster.
    uses: azure/aks-set-context@v1
    with:
      resource-group: adoptium-api
      cluster-name: adoptium-api

  - name: Deploy to AKS
    shell: bash
    run: |
      kubectl set image deployment/${{ inputs.K8S_DEPLOYMENT }} \
        -n ${{ inputs.K8S_NAMESPACE }} \
        ${{ inputs.K8S_DEPLOYMENT }}=${{ inputs.DOCKER_REPO }}:latest
